# logininfo schema

# --- !Ups

CREATE TABLE logininfo (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
    providerID        VARCHAR NOT NULL,
    providerKey       VARCHAR NOT NULL
);

# --- !Downs

DROP TABLE logininfo;